spring:
  application:
    name: user-thrift-service
  datasource:
    url: jdbc:mysql://192.168.1.98:3306/db_user?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8000
